name: "Packaging (el10)"

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
    name: Build Package
    runs-on: ${{ matrix.os }}
    container: rockylinux/rockylinux:10-minimal
    steps:
      - name: Install Dependencies
        run: |
          microdnf -y install dnf epel-release
          /usr/bin/crb enable
          dnf -y install git rpm-build rpm-sign make systemd-rpm-macros opencv-devel gcc gpg

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Package RPM
        run: make

      - name: Clone Package Repository
        uses: actions/checkout@v4
        with:
          repository: rockit-astro/el10
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: packages

      - name: Sign and Push Packages
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
        run: packages/sign-and-push-packages.sh *.rpm
