name: RPM Packaging

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: RPM Packaging
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2.1.0
      - name: Package x86_64 RPM
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: rockylinux:9
          shell: /bin/bash
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          run: |
            cat /etc/redhat-release
            yum -y install epel-release
            yum -y config-manager --set-enabled crb
            yum -y install rpm-build rpm-sign make systemd-rpm-macros opencv-devel gcc
            make
            mv *.rpm /artifacts
      - name: Package aarch64 RPM
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: arm64v8/rockylinux:9
          shell: /bin/bash
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          run: |
            cat /etc/redhat-release
            yum -y install epel-release
            yum -y config-manager --set-enabled crb
            yum -y install rpm-build rpm-sign make systemd-rpm-macros opencv-devel gcc
            make
            mv *.rpm /artifacts
      - name: Clone Package Repository
        uses: actions/checkout@v2
        with:
          repository: warwick-one-metre/rocky-packages
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: rocky-packages
      - name: Push Packages
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
        run: |
          rocky-packages/sign-and-push-packages.sh artifacts/*.rpm

